version: "3.8"
services:
  vote: 
    build: .
    image: dockersamples/examplevotingapp_vote:before
    ports: 
      - "5000:80"
    networks:
      - frontend
  
  redis: 
    build: .
    image: redis:3.2   
    networks:
      - frontend
  
  worker:
    build: .
    image: dockersamples/examplevotingapp_worker          
    networks:
      - frontend
      - backend

  db: 
    build: .
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust          
    networks:
      - backend
    volumes:
      - /var/lib/postgresql/data

  result: 
    build: .
    image: dockersamples/examplevotingapp_result:before           
    ports: 
      - "5001:80"
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  db-data: